openapi: 3.0.0
info:
  title: Selection Engine API
  description: An API for manipulating selectors and references of stand-off annotations 
  version: 0.1.0

paths:
  /wadm/normalize:
    post:
      summary: normalizes the supplied WADM annotation
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                model:
                  description: the RDF data
                  type: string
                  format: binary
                source:
                  description: optional source instead of oa:hasSource
                  type: string
                  format: binary
                config:
                  $ref: '#/components/schemas/config'
              required:
                - model
            encoding:
              model:
                contentType: application/rdf+xml, application/xml, application/x-binary-rdf, text/turtle, application/x-turtle, text/n3, text/rdf+n3, application/rdf+json, application/ld+json, application/x-trig, application/x-trig, application/trix
              source:
                contentType: text/html, application/xhtml+xml, text/xml, application/xml
      responses:
        200:
          $ref: '#/components/responses/ModelProcessed'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalError'
        
components:
  schemas:
    config:
      description: Per request config options
      type: object
      properties:
        xpath:
          description: XPath for determining the new XPath component of XPathSelectors
          type: string
        xpathPre:
          description: predefined XPath
          type: string

  responses:
    ModelProcessed:
      description: OK
      content:
        application/rdf+xml:
          schema:
            type: string
            format: binary
        application/xml:
          schema:
            type: string
            format: binary
        application/x-binary-rdf:
          schema:
            type: string
            format: binary
        text/turtle:
          schema:
            type: string
            format: binary
        application/x-turtle:
          schema:
            type: string
            format: binary
        text/n3:
          schema:
            type: string
            format: binary
        application/rdf+json:
          schema:
            type: string
            format: binary
        application/ld+json:
          schema:
            type: string
            format: binary
        application/x-trig:
          schema:
            type: string
            format: binary
        application/trix:
          schema:
            type: string
            format: binary
    NotFound:
      description: The specified resource was not found
    BadRequest:
      description: Bad request.
      content:
        text/plain:
          schema:
            type: string
            format: binary
    InternalError:
      description: An error occurred while performing the transformation.
      content:
        text/plain:
          schema:
            type: string
            format: binary
