package de.wwu.scdh.annotation.selection;

import java.util.List;
import java.util.Optional;


/**
 * A {@link MappedResource} is a {@link Resource}, for which there is
 * a derivation or mapping generated by some derivation mechanism,
 * e.g., XSLT. The resource is the preimage, while the mapped image is
 * accessible via {@link MappedResource.getImage()}.<P>
 *
 * Type parameters:<P>
 *
 * <code>T1</code>, <code>T2</code>: parsed content types of the
 * preimage and image resources. E.g., XdmNode for DOMResources.<P>
 *
 * <code>A1</code>, <code>A2</code>: content partes of the preimage
 * and image. E.g., XdmNode for DOMResources.<P>
 *
 * <code>P1</code>, <code>P2</code>: {@link Point} in preimage and
 * image.<P>
 *
 * In a {@link DOMResource}, the parsed content type Tx and part type
 * Ax will be the same. But this is not the case in general.
 */
public interface MappedResource<T1, T2, A1, A2> extends Resource<T1> {

    /**
     * Returns the image.
     */
    Resource<T2> getImage();

    /**
     * For a given part in the preimage, this returns the
     * corresponding part in the image. Since the image may contain
     * multiple copies of the same part of the preimage, a list of
     * parts is returned.
     */
    List<A2> getCorrespondingInImage(A1 preimagePart);

    /**
     * For a given part in the image, this returns the corresponting
     * part in the preimage.
     */
    Optional<A1> getCorrespondingInPreimage(A2 imagePart);

}
