name: Create release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-?**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK, for pushing into github package registry
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Push to Github package registry
        run: mvn -Drevision=${{ github.ref_name }} -Dchangelist="" --batch-mode --update-snapshots deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release with release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              core/target/*.tar.gz \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag}" \
              --generate-notes

      - name: Create Java Docs
        run: mvn -Drevision=${{ github.ref_name }} -Dchangelist="" --batch-mode javadoc:aggregate

      - name: Zip Java Docs
        run: |
          cd target/site/apidocs
          zip -r apidocs.zip *

      - name: Store Java Docs as gh artifact
        uses: actions/download-artifact@v4
        with:
          name: apidocs
          path: target/site/apidocs/apidocs.zip
          retention-days: 1

  pages:
    name: Github pages
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:

      - name: Create directory for gh pages
        run: mkdir -p public

      - name: Download apidocs artifact
        uses: actions/download-artifact@v4
        with:
          name: apidocs

      - name: Unzip apidocs artifact
        run: unzip apidocs.zip -d public

      - name: Deploy on Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public